[log]
level = "DEBUG"

# [agent]
reasoning_model = "gpt-4o-mini"
use_vision = false
# max_history_tokens = ...
max_actions_per_step = 1
history_type = "short_observations_with_short_data"
max_steps = 100
human_in_the_loop = false

#[error]
max_error_length = 500
raise_condition = "retry"
max_consecutive_failures = 3

# [browser]
headless = false
# user_agent = null
# viewport_width = null
# viewport_height = null
browser_type = "chromium"
# chrome_args = null
web_security = false
# cdp_url = null
cdp_debug = false
# custom_devtools_frontend = null

# [proxy]
# proxy_host = null
# proxy_port = null
# proxy_username = null
# proxy_password = null

# [llm]
structured_output_retries = 2
nb_retries = 2
clip_tokens=5000

# [scraping]
scraping_model = "gpt-4o-mini"
auto_scrape = true
include_links = true
include_ids = false
use_llm = true
rendering = "markdown"

# [perception]
perception_enabled = true
perception_model = "gpt-4o-mini"
